language: node_js
node_js:
  - 7
addons:
  sauce_connect: true
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build
  on:
    branch: master